---
# For RedHat/CentOS, see notes in README.
- name: Enable mod_proxy_fcgi.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
    mode: 0644
  with_items:
    - proxy.load
    - proxy_fcgi.load
  notify: restart apache
  when: ansible_os_family == 'Debian'
