---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_listen_port_ssl: 443
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - servername: "example.com"
        documentroot: "/var/www/vhosts/example_com"

  roles:
    - role: nholuong.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: nholuong.apache
    - role: nholuong.php-versions
    - role: nholuong.php
    - role: nholuong.apache-php-fpm
